# @file .github/workflows/UpdateForUbuntu.yml
#
# Copyright (c) 2023+ TIB Hannover
# Copyright (c) 2023+ Gazi Yucel
# Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
#
# @brief Submodule to be used in the Open Journal Systems plugin latexConverter.

name: UpdateForUbuntu

on:
  # schedule:
  # cron format: minute, hour, day of the month, month, day of the week
  # - cron: "0 6 * * *"
  workflow_dispatch: ~

env:
  GITHUB_TOKEN: ${{ github.token }}
  GITHUB_USERNAME: ${{ github.actor }}

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: execute UpdateForUbuntu.sh
        run: |
          echo "sh ./UpdateForUbuntu.sh $GITHUB_USERNAME"
          sh ./UpdateForUbuntu.sh "$GITHUB_USERNAME" "$GITHUB_TOKEN"
